#!/bin/bash --login
#
#PBS -N CASTEP_DNA
#PBS -l select=500
#PBS -l walltime=3:0:0
#PBS -A z17

cd $PBS_O_WORKDIR

module load castep/16.1.2

INPUT_DIR=/home/z17/z17/jenkins/ci-monitoring/monitoring/apps/castep/run
RES_DIR=/home/z17/z17/jenkins/ci-monitoring/monitoring/apps/castep/results
WORK_DIR=/work/z17/z17/jenkins/ci-monitoring/apps/castep

cd ${WORK_DIR}

cp ${INPUT_DIR}/* .

export OMP_NUM_THREADS=6
aprun -n 2000 -N 4 -d 6 castep.mpi polyA20-no-wat

timestamp=$(date '+%Y%m%d%H%M%S')
outfile=${RES_DIR}/castep_res_${timestamp}.castep
mv polyA20-no-wat.castep ${outfile}

